// <auto-generated />
using System;
using LP2Parcial2API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LP2Parcial2API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308042709_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LP2Parcial2API.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<double>("PrecioUnitario")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("ItemsPedido");
                });

            modelBuilder.Entity("LP2Parcial2API.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("DescuentoUsado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("TotalFinal")
                        .HasColumnType("float");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("LP2Parcial2API.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Pasteles",
                            Description = "Tope de mermelada de mango, manzana y almíbar.",
                            Price = 550.0,
                            Rating = 4.7000000000000002,
                            Thumbnail = "images/productos/pastelmango.jpg",
                            Title = "Cheesecake de mango y manzana"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Pasteles",
                            Description = "Relleno de crema pastelera con fresas en el tope.",
                            Price = 650.0,
                            Rating = 4.9000000000000004,
                            Thumbnail = "images/productos/pastelredvelvet.jpg",
                            Title = "Pastel Red Velvet"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Pasteles",
                            Description = "Relleno de fresas, crema pastelera y fresas en el tope.",
                            Price = 650.0,
                            Rating = 4.9000000000000004,
                            Thumbnail = "images/productos/pastelfresa.jpg",
                            Title = "Pastel de fresa"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Pasteles",
                            Description = "Relleno de crema pastelera con chocolate rallado en el tope.",
                            Price = 650.0,
                            Rating = 4.9000000000000004,
                            Thumbnail = "images/productos/pastelchocolate.jpg",
                            Title = "Pastel de chocolate"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Donas",
                            Description = "Relleno de mermelada de fresa. Azúcar glass en el tope.",
                            Price = 70.0,
                            Rating = 4.4000000000000004,
                            Thumbnail = "images/productos/donutfresa.jpg",
                            Title = "Donut de fresa"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Donas",
                            Description = "Donut clásico con glaseado de azúcar.",
                            Price = 50.0,
                            Rating = 4.2000000000000002,
                            Thumbnail = "images/productos/donutglaseado.jpg",
                            Title = "Donut glaseado"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Donas",
                            Description = "Relleno de nutella. Azúcar glass en el tope.",
                            Price = 70.0,
                            Rating = 4.7999999999999998,
                            Thumbnail = "images/productos/donutnutella.jpg",
                            Title = "Donut de nutella"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Donas",
                            Description = "Donut clásico de fresa con glaseado. Sprinkles en el tope.",
                            Price = 50.0,
                            Rating = 4.2999999999999998,
                            Thumbnail = "images/productos/donutglaseadofresa.jpg",
                            Title = "Donut glaseado de fresa"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Waffles",
                            Description = "Waffle clásico con mantequilla en el tope.",
                            Price = 150.0,
                            Rating = 3.8999999999999999,
                            Thumbnail = "images/productos/wafflebasico.jpg",
                            Title = "Waffle clásico"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Waffles",
                            Description = "Helado de vainilla y syrup de chocolate en el tope.",
                            Price = 300.0,
                            Rating = 4.7000000000000002,
                            Thumbnail = "images/productos/wafflechocolate.jpg",
                            Title = "Waffle de chocolate"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Waffles",
                            Description = "Fresas y syrup de maple en el tope.",
                            Price = 150.0,
                            Rating = 4.0,
                            Thumbnail = "images/productos/wafflefresa.jpg",
                            Title = "Waffle de fresa"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Waffles",
                            Description = "Helado de vainilla en el tope.",
                            Price = 150.0,
                            Rating = 4.5999999999999996,
                            Thumbnail = "images/productos/wafflehelado.jpg",
                            Title = "Waffle con helado"
                        });
                });

            modelBuilder.Entity("LP2Parcial2API.Models.ItemPedido", b =>
                {
                    b.HasOne("LP2Parcial2API.Models.Pedido", "Pedido")
                        .WithMany("Items")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("LP2Parcial2API.Models.Pedido", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
